String role = "";
String? userName;
List<String> allQuestions = [
  "Who is the most likely to die soon",
  "Most likely to forget their best friend's birthday",
  "Most likely to eat something off the ground",
  "Most likely to break a world record",
  "Most likely to become a millionaire",
  "Most likely to spend all their money on something stupid",
  "Most likely to marry a celebrity",
  "Most likely to commit a crime",
  "Most likely to fake their own death",
  "Most likely to become an influencer",
  "Most likely to get lost in their own hometown",
  "Most likely to get caught having sex in public",
  "Most likely to sleep with their ex",
  "Most likely to become prime minister",
  "Most likely to give their kid a terrible name",
  "Most likely to poison someone with terrible cooking",
  "Most likely to join a cult",
  "Most likely to have an affair",
  "Will reveal the last thing they searched on their phone?",
  "Has peed in the pool?",
  "Who would you trade lives with?",
  "Has practiced kissing in a mirror?",
  "Will tell their guilty pleasure",
  "Will tell their biggest sexual fear?",
  "Will tell their most flirtatious thing ever done?",
  "Will tell three adjectives that best describe their vagina/penis?",
  "Will tell the weirdest thing they've done in front of the mirror?",
  "Will tell the cruelest thing they’ve ever done to a friend?",
  "Will tell the most childish thing they still do?",
  "Who do you look up to more?",
  "Will tell their all-time favorite memory?",
  "Will tell the last person who made them cry and why?",
  "Who are you closer to?",
  "Will tell one thing most people don’t know about them?",
  "Will tell a shameful secret",
  "Will tell what book has impacted them the most?",
];
